/*
 *  gl_shaders_gles.h - OpenGL 1.2 FFP uber-shader as GLSL ES 3.00 strings
 *
 *  Ported from PocketShaver gl_shaders.metal (C) 2026 Sierra Burkhart
 *  GLSL ES 3.00 (prepended with #version 300 es in gl_gles_renderer.cpp)
 *
 *  Single uniform-driven program implementing:
 *    - MVP + modelview + normal matrix transforms
 *    - Per-vertex Phong lighting for up to 8 lights
 *    - 5 texture environment modes (modulate, decal, blend, replace, add)
 *    - 3 fog modes (linear, exp, exp2)
 *    - Alpha test with all 8 comparison functions
 *
 *  Vertex layout (52 bytes, matches GLGLESVertex struct):
 *    attribute 0: vec4 a_position  (x, y, z, w)
 *    attribute 1: vec4 a_color     (r, g, b, a)
 *    attribute 2: vec3 a_normal    (nx, ny, nz)
 *    attribute 3: vec2 a_texcoord  (s, t)
 */

#ifndef GL_SHADERS_GLES_H
#define GL_SHADERS_GLES_H

static const char *gl_vertex_src =
	"precision highp float;\n"
	"\n"
	"in vec4 a_position;\n"
	"in vec4 a_color;\n"
	"in vec3 a_normal;\n"
	"in vec2 a_texcoord;\n"
	"\n"
	"// Vertex uniforms\n"
	"uniform mat4 u_mvp_matrix;\n"
	"uniform mat4 u_modelview_matrix;\n"
	"uniform mat3 u_normal_matrix;\n"
	"uniform int u_lighting_enabled;\n"
	"uniform int u_normalize_enabled;\n"
	"uniform int u_fog_enabled;\n"
	"uniform int u_fog_mode;\n"
	"uniform float u_fog_start;\n"
	"uniform float u_fog_end;\n"
	"uniform float u_fog_density;\n"
	"\n"
	"// Lighting uniforms (8 lights)\n"
	"struct Light {\n"
	"    vec4 ambient;\n"
	"    vec4 diffuse;\n"
	"    vec4 specular;\n"
	"    vec4 position;\n"
	"    vec3 spot_direction;\n"
	"    float spot_exponent;\n"
	"    float spot_cutoff;\n"
	"    float constant_atten;\n"
	"    float linear_atten;\n"
	"    float quadratic_atten;\n"
	"    int enabled;\n"
	"};\n"
	"uniform Light u_lights[8];\n"
	"\n"
	"// Material uniforms\n"
	"uniform vec4 u_mat_ambient;\n"
	"uniform vec4 u_mat_diffuse;\n"
	"uniform vec4 u_mat_specular;\n"
	"uniform vec4 u_mat_emission;\n"
	"uniform float u_mat_shininess;\n"
	"uniform vec4 u_global_ambient;\n"
	"\n"
	"out vec4 v_color;\n"
	"out vec2 v_texcoord;\n"
	"out float v_fog_factor;\n"
	"\n"
	"void main() {\n"
	"    gl_Position = u_mvp_matrix * a_position;\n"
	"\n"
	"    vec4 eye_pos = u_modelview_matrix * a_position;\n"
	"\n"
	"    vec3 eye_normal = u_normal_matrix * a_normal;\n"
	"    if (u_normalize_enabled != 0) {\n"
	"        float len = length(eye_normal);\n"
	"        if (len > 0.0) eye_normal /= len;\n"
	"    }\n"
	"\n"
	"    v_texcoord = a_texcoord;\n"
	"    gl_PointSize = 1.0;\n"
	"\n"
	"    if (u_lighting_enabled != 0) {\n"
	"        vec4 color = u_mat_emission + u_global_ambient * u_mat_ambient;\n"
	"\n"
	"        for (int i = 0; i < 8; i++) {\n"
	"            if (u_lights[i].enabled == 0) continue;\n"
	"\n"
	"            vec3 L;\n"
	"            float attenuation = 1.0;\n"
	"            if (u_lights[i].position.w == 0.0) {\n"
	"                L = normalize(u_lights[i].position.xyz);\n"
	"            } else {\n"
	"                vec3 lightVec = u_lights[i].position.xyz - eye_pos.xyz;\n"
	"                float dist = length(lightVec);\n"
	"                L = lightVec / max(dist, 0.0001);\n"
	"                attenuation = 1.0 / (u_lights[i].constant_atten +\n"
	"                                     u_lights[i].linear_atten * dist +\n"
	"                                     u_lights[i].quadratic_atten * dist * dist);\n"
	"            }\n"
	"\n"
	"            float spotEffect = 1.0;\n"
	"            if (u_lights[i].spot_cutoff >= 0.0) {\n"
	"                float spotCos = dot(-L, normalize(u_lights[i].spot_direction));\n"
	"                if (spotCos < u_lights[i].spot_cutoff) {\n"
	"                    spotEffect = 0.0;\n"
	"                } else {\n"
	"                    spotEffect = pow(spotCos, u_lights[i].spot_exponent);\n"
	"                }\n"
	"            }\n"
	"\n"
	"            vec4 ambient_c = u_lights[i].ambient * u_mat_ambient;\n"
	"            float NdotL = max(dot(eye_normal, L), 0.0);\n"
	"            vec4 diffuse_c = NdotL * u_lights[i].diffuse * u_mat_diffuse;\n"
	"\n"
	"            vec4 specular_c = vec4(0.0);\n"
	"            if (NdotL > 0.0 && u_mat_shininess > 0.0) {\n"
	"                vec3 V = normalize(-eye_pos.xyz);\n"
	"                vec3 H = normalize(L + V);\n"
	"                float NdotH = max(dot(eye_normal, H), 0.0);\n"
	"                float spec = pow(NdotH, u_mat_shininess);\n"
	"                specular_c = spec * u_lights[i].specular * u_mat_specular;\n"
	"            }\n"
	"\n"
	"            color += attenuation * spotEffect * (ambient_c + diffuse_c + specular_c);\n"
	"        }\n"
	"\n"
	"        v_color = clamp(color, 0.0, 1.0);\n"
	"    } else {\n"
	"        v_color = a_color;\n"
	"    }\n"
	"\n"
	"    if (u_fog_enabled != 0) {\n"
	"        float dist = abs(eye_pos.z);\n"
	"        float fog_f = 1.0;\n"
	"        if (u_fog_mode == 1) {\n"
	"            fog_f = (u_fog_end - dist) / (u_fog_end - u_fog_start);\n"
	"        } else if (u_fog_mode == 2) {\n"
	"            fog_f = exp(-u_fog_density * dist);\n"
	"        } else if (u_fog_mode == 3) {\n"
	"            float dz = u_fog_density * dist;\n"
	"            fog_f = exp(-dz * dz);\n"
	"        }\n"
	"        v_fog_factor = clamp(fog_f, 0.0, 1.0);\n"
	"    } else {\n"
	"        v_fog_factor = 1.0;\n"
	"    }\n"
	"    gl_PointSize = 1.0;\n"
	"}\n";

static const char *gl_fragment_src =
	"precision mediump float;\n"
	"\n"
	"in vec4 v_color;\n"
	"in vec2 v_texcoord;\n"
	"in float v_fog_factor;\n"
	"\n"
	"out vec4 fragColor;\n"
	"\n"
	"uniform int u_texenv_mode;\n"
	"uniform vec4 u_texenv_color;\n"
	"uniform vec4 u_fog_color;\n"
	"uniform int u_alpha_test_enabled;\n"
	"uniform int u_alpha_func;\n"
	"uniform float u_alpha_ref;\n"
	"uniform int u_has_texture;\n"
	"uniform sampler2D u_texture0;\n"
	"\n"
	"\n"
	"void main() {\n"
	"    vec4 color = v_color;\n"
	"\n"
	"    if (u_has_texture != 0) {\n"
	"        vec4 tex_color = texture(u_texture0, v_texcoord);\n"
	"\n"
	"        if (u_texenv_mode == 0) {\n"
	"            color = vec4(color.rgb * tex_color.rgb, color.a * tex_color.a);\n"
	"        } else if (u_texenv_mode == 1) {\n"
	"            color.rgb = mix(color.rgb, tex_color.rgb, tex_color.a);\n"
	"        } else if (u_texenv_mode == 2) {\n"
	"            color.rgb = mix(color.rgb, u_texenv_color.rgb, tex_color.rgb);\n"
	"            color.a *= tex_color.a;\n"
	"        } else if (u_texenv_mode == 3) {\n"
	"            color = tex_color;\n"
	"        } else if (u_texenv_mode == 4) {\n"
	"            color.rgb = clamp(color.rgb + tex_color.rgb, 0.0, 1.0);\n"
	"            color.a *= tex_color.a;\n"
	"        }\n"
	"    }\n"
	"\n"
	"    if (u_fog_color.w > -0.5) {\n"
	"        color.rgb = mix(u_fog_color.rgb, color.rgb, v_fog_factor);\n"
	"    }\n"
	"\n"
	"    if (u_alpha_test_enabled != 0) {\n"
	"        bool pass = true;\n"
	"        float ref = u_alpha_ref;\n"
	"        if (u_alpha_func == 0) {\n"
	"            pass = false;\n"
	"        } else if (u_alpha_func == 1) {\n"
	"            pass = (color.a < ref);\n"
	"        } else if (u_alpha_func == 2) {\n"
	"            pass = (color.a == ref);\n"
	"        } else if (u_alpha_func == 3) {\n"
	"            pass = (color.a <= ref);\n"
	"        } else if (u_alpha_func == 4) {\n"
	"            pass = (color.a > ref);\n"
	"        } else if (u_alpha_func == 5) {\n"
	"            pass = (color.a != ref);\n"
	"        } else if (u_alpha_func == 6) {\n"
	"            pass = (color.a >= ref);\n"
	"        }\n"
	"        if (!pass) discard;\n"
	"    }\n"
	"\n"
	"    fragColor = color;\n"
	"}\n";

#endif /* GL_SHADERS_GLES_H */
