/*
 *  rave_shaders_gles.h - RAVE GLSL ES 1.00 shader source strings
 *
 *  Ported from PocketShaver rave_shaders.metal (C) 2026 Sierra Burkhart
 *  GLSL ES 3.00 sources (prepended with #version 300 es in rave_gles_renderer.cpp)
 *
 *  The renderer compiles 16 program variants at init time by prepending
 *  #define lines before these sources:
 *    HAS_TEXTURE, HAS_FOG, HAS_ALPHA_TEST, HAS_MULTI_TEXTURE
 *
 *  Vertex layout (48 bytes, matches RaveVertex struct):
 *    attribute 0: vec4 a_position  (x, y, z, w)
 *    attribute 1: vec4 a_color     (r, g, b, a)
 *    attribute 2: vec4 a_texcoord  (uOverW, vOverW, invW, 0)
 *  Multi-texture UV2 (when HAS_MULTI_TEXTURE):
 *    attribute 3: vec4 a_texcoord2 (uOverW2, vOverW2, invW2, 0)
 */

#ifndef RAVE_SHADERS_GLES_H
#define RAVE_SHADERS_GLES_H

static const char *rave_vertex_src =
	"precision highp float;\n"
	"in vec4 a_position;\n"
	"in vec4 a_color;\n"
	"in vec4 a_texcoord;\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"in vec4 a_texcoord2;\n"
	"#endif\n"
	"\n"
	"uniform vec4 u_viewport;\n"
	"uniform float u_point_width;\n"
	"\n"
	"out vec4 v_color;\n"
	"out vec4 v_texcoord;\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"out vec4 v_texcoord2;\n"
	"#endif\n"
	"\n"
	"void main() {\n"
	"    gl_Position.x = (a_position.x / u_viewport.x) * 2.0 - 1.0;\n"
	"    gl_Position.y = 1.0 - (a_position.y / u_viewport.y) * 2.0;\n"
	"    gl_Position.z = clamp(a_position.z, 0.0, 1.0) * 1.998 - 0.999;\n"
	"    gl_Position.w = 1.0;\n"
	"    gl_PointSize = u_point_width;\n"
	"    v_color = a_color;\n"
	"#if defined(HAS_TEXTURE) || defined(HAS_FOG)\n"
	"    v_texcoord = a_texcoord;\n"
	"#endif\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"    v_texcoord2 = a_texcoord2;\n"
	"#endif\n"
	"}\n";

static const char *rave_fragment_src =
	"precision mediump float;\n"
	"\n"
	"in vec4 v_color;\n"
	"in vec4 v_texcoord;\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"in vec4 v_texcoord2;\n"
	"#endif\n"
	"\n"
	"out vec4 fragColor;\n"
	"\n"
	"#ifdef HAS_TEXTURE\n"
	"uniform sampler2D u_texture0;\n"
	"#endif\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"uniform sampler2D u_texture1;\n"
	"#endif\n"
	"\n"
	"uniform int u_texture_op;\n"
	"#ifdef HAS_FOG\n"
	"uniform int u_fog_mode;\n"
	"uniform vec4 u_fog_color;\n"
	"uniform float u_fog_start;\n"
	"uniform float u_fog_end;\n"
	"uniform float u_fog_density;\n"
	"uniform float u_fog_max_depth;\n"
	"#endif\n"
	"#ifdef HAS_ALPHA_TEST\n"
	"uniform int u_alpha_test_func;\n"
	"uniform float u_alpha_test_ref;\n"
	"#endif\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"uniform int u_multi_texture_op;\n"
	"uniform float u_multi_texture_factor;\n"
	"#endif\n"
	"uniform vec4 u_env_color;\n"
	"\n"
	"bool bitSet(int val, int bit) {\n"
	"    return mod(floor(float(val) / float(bit)), 2.0) >= 1.0;\n"
	"}\n"
	"\n"
	"void main() {\n"
	"    vec4 color = v_color;\n"
	"\n"
	"#ifdef HAS_TEXTURE\n"
	"    vec2 uv;\n"
	"    if (v_texcoord.z > 0.0) {\n"
	"        uv = vec2(v_texcoord.x / v_texcoord.z,\n"
	"                  v_texcoord.y / v_texcoord.z);\n"
	"    } else {\n"
	"        uv = vec2(0.0, 0.0);\n"
	"    }\n"
	"    vec4 texPix = texture(u_texture0, uv);\n"
	"\n"
	"    if (bitSet(u_texture_op, 4)) {\n"
	"        texPix.rgb = texPix.a * texPix.rgb + (1.0 - texPix.a) * color.rgb;\n"
	"        texPix.a = color.a;\n"
	"    } else if (bitSet(u_texture_op, 16)) {\n"
	"        texPix.rgb = (1.0 - texPix.rgb) * u_env_color.rgb + texPix.rgb * color.rgb;\n"
	"        texPix.a *= color.a;\n"
	"    } else if (bitSet(u_texture_op, 1)) {\n"
	"        texPix.rgb = clamp(texPix.rgb * color.rgb, 0.0, 1.0);\n"
	"        texPix.a *= color.a;\n"
	"    } else {\n"
	"        texPix.a *= color.a;\n"
	"    }\n"
	"    if (bitSet(u_texture_op, 2)) {\n"
	"        texPix.rgb = clamp(texPix.rgb + color.rgb, 0.0, 1.0);\n"
	"    }\n"
	"    color = texPix;\n"
	"#endif\n"
	"\n"
	"#ifdef HAS_MULTI_TEXTURE\n"
	"    vec2 uv2;\n"
	"    if (v_texcoord2.z > 0.0) {\n"
	"        uv2 = vec2(v_texcoord2.x / v_texcoord2.z,\n"
	"                   v_texcoord2.y / v_texcoord2.z);\n"
	"    } else {\n"
	"        uv2 = vec2(0.0, 0.0);\n"
	"    }\n"
	"    vec4 tex2Color = texture(u_texture1, uv2);\n"
	"    if (u_multi_texture_op == 0)\n"
	"        color.rgb = clamp(color.rgb + tex2Color.rgb, 0.0, 1.0);\n"
	"    else if (u_multi_texture_op == 1)\n"
	"        color.rgb *= tex2Color.rgb;\n"
	"    else if (u_multi_texture_op == 2)\n"
	"        color.rgb = mix(color.rgb, tex2Color.rgb, tex2Color.a);\n"
	"    else if (u_multi_texture_op == 3)\n"
	"        color.rgb = mix(color.rgb, tex2Color.rgb, u_multi_texture_factor);\n"
	"#endif\n"
	"\n"
	"#ifdef HAS_ALPHA_TEST\n"
	"    bool pass = true;\n"
	"    if (u_alpha_test_func == 1)\n"
	"        pass = (color.a < u_alpha_test_ref);\n"
	"    else if (u_alpha_test_func == 2)\n"
	"        pass = (color.a == u_alpha_test_ref);\n"
	"    else if (u_alpha_test_func == 3)\n"
	"        pass = (color.a <= u_alpha_test_ref);\n"
	"    else if (u_alpha_test_func == 4)\n"
	"        pass = (color.a > u_alpha_test_ref);\n"
	"    else if (u_alpha_test_func == 5)\n"
	"        pass = (color.a != u_alpha_test_ref);\n"
	"    else if (u_alpha_test_func == 6)\n"
	"        pass = (color.a >= u_alpha_test_ref);\n"
	"    if (!pass) discard;\n"
	"#endif\n"
	"\n"
	"#ifdef HAS_FOG\n"
	"    float fog_factor = 1.0;\n"
	"    if (u_fog_mode == 1) {\n"
	"        fog_factor = color.a;\n"
	"    } else if (u_fog_mode == 2) {\n"
	"        float z = (v_texcoord.z > 0.0) ? (1.0 / v_texcoord.z) : (gl_FragCoord.z * u_fog_max_depth);\n"
	"        fog_factor = clamp((u_fog_end - z) / (u_fog_end - u_fog_start), 0.0, 1.0);\n"
	"    } else if (u_fog_mode == 3) {\n"
	"        float z = (v_texcoord.z > 0.0) ? (1.0 / v_texcoord.z) : (gl_FragCoord.z * u_fog_max_depth);\n"
	"        fog_factor = clamp(exp(-u_fog_density * z), 0.0, 1.0);\n"
	"    } else if (u_fog_mode == 4) {\n"
	"        float z = (v_texcoord.z > 0.0) ? (1.0 / v_texcoord.z) : (gl_FragCoord.z * u_fog_max_depth);\n"
	"        float dz = u_fog_density * z;\n"
	"        fog_factor = clamp(exp(-dz * dz), 0.0, 1.0);\n"
	"    }\n"
	"    color.rgb = mix(u_fog_color.rgb, color.rgb, fog_factor);\n"
	"    if (u_fog_mode == 1) {\n"
	"        color.a = 1.0;\n"
	"    }\n"
	"#endif\n"
	"\n"
	"    fragColor = color;\n"
	"}\n";

#endif /* RAVE_SHADERS_GLES_H */
